CREATE TABLE zendesk (
	TimePeriod VARCHAR(19), 
	IndicatorType VARCHAR(19), 
	Name VARCHAR(50) NOT NULL, 
	HTML VARCHAR(4) NOT NULL, 
	JSON VARCHAR(4) NOT NULL, 
	CSV VARCHAR(3) NOT NULL, 
	XML VARCHAR(3) NOT NULL, 
	SqlView VARCHAR(11) NOT NULL, 
	Dataset VARCHAR(11), 
	Notes VARCHAR(134)
);