class DatimConstants:

    # Import batch IDs
    IMPORT_BATCH_MER = 'MER'
    IMPORT_BATCH_SIMS = 'SIMS'
    IMPORT_BATCH_MECHANISMS = 'Mechanisms'
    IMPORT_BATCH_TIERED_SUPPORT = 'Tiered-Support'  # Tiered Support is imported with init scripts, not a sync script

    # MER OCL Export Definitions
    MER_OCL_EXPORT_DEFS = {
        'MER': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/sources/MER/'},
        'MER-R-Facility-DoD-FY17Q1': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Facility-DoD-FY17Q1/'},
        'MER-R-Facility-DoD-FY17Q2': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Facility-DoD-FY17Q2/'},
        'MER-R-Facility-DoD-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Facility-DoD-FY16Q4/'},
        'HC-R-COP-Prioritization-SNU-USG-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-R-COP-Prioritization-SNU-USG-FY16Q4/'},
        'HC-R-Narratives-USG-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-R-Narratives-USG-FY16Q1Q2Q3/'},
        'HC-R-Narratives-USG-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-R-Narratives-USG-FY16Q4/'},
        'HC-R-Narratives-USG-FY17Q1': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-R-Narratives-USG-FY17Q1/'},
        'HC-R-Narratives-USG-FY17Q2': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-R-Narratives-USG-FY17Q2/'},
        'HC-R-Operating-Unit-Level-USG-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-R-Operating-Unit-Level-USG-FY16Q1Q2Q3/'},
        'HC-R-Operating-Unit-Level-USG-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-R-Operating-Unit-Level-USG-FY16Q4/'},
        'HC-T-COP-Prioritization-SNU-USG-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-T-COP-Prioritization-SNU-USG-FY17/'},
        'HC-T-COP-Prioritization-SNU-USG-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-T-COP-Prioritization-SNU-USG-FY18/'},
        'HC-T-Narratives-USG-FY16': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-T-Narratives-USG-FY16/'},
        'HC-T-Narratives-USG-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-T-Narratives-USG-FY17/'},
        'HC-T-Operating-Unit-Level-USG-FY16': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-T-Operating-Unit-Level-USG-FY16/'},
        'HC-T-Operating-Unit-Level-USG-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-T-Operating-Unit-Level-USG-FY17/'},
        'HC-T-Operating-Unit-Level-USG-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/HC-T-Operating-Unit-Level-USG-FY18/'},
        'MER-R-Community-DoD-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Community-DoD-FY16Q1Q2Q3/'},
        'MER-R-Community-DoD-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Community-DoD-FY16Q4/'},
        'MER-R-Community-DoD-FY17Q1': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Community-DoD-FY17Q1/'},
        'MER-R-Community-DoD-FY17Q2': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Community-DoD-FY17Q2/'},
        'MER-R-Community-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Community-FY16Q1Q2Q3/'},
        'MER-R-Community-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Community-FY16Q4/'},
        'MER-R-Community-FY17Q1': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Community-FY17Q1/'},
        'MER-R-Community-FY17Q2': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Community-FY17Q2/'},
        'MER-R-Facility-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Facility-FY16Q1Q2Q3/'},
        'MER-R-Facility-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Facility-FY16Q4/'},
        'MER-R-Facility-FY17Q1': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Facility-FY17Q1/'},
        'MER-R-Facility-FY17Q2': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Facility-FY17Q2/'},
        'MER-R-Medical-Store-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Medical-Store-FY16Q1Q2Q3/'},
        'MER-R-Medical-Store-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Medical-Store-FY16Q4/'},
        'MER-R-Medical-Store-FY17Q1': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Medical-Store-FY17Q1/'},
        'MER-R-Narratives-IM-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Narratives-IM-FY16Q1Q2Q3/'},
        'MER-R-Narratives-IM-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Narratives-IM-FY16Q4/'},
        'MER-R-Narratives-IM-FY17Q1': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Narratives-IM-FY17Q1/'},
        'MER-R-Narratives-IM-FY17Q2': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Narratives-IM-FY17Q2/'},
        'MER-R-Operating-Unit-Level-IM-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Operating-Unit-Level-IM-FY16Q1Q2Q3/'},
        'MER-R-Operating-Unit-Level-IM-FY16Q4': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Operating-Unit-Level-IM-FY16Q4/'},
        'MER-R-Operating-Unit-Level-IM-FY17Q1': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Operating-Unit-Level-IM-FY17Q1/'},
        'MER-R-Operating-Unit-Level-IM-FY17Q2': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Operating-Unit-Level-IM-FY17Q2/'},
        'MER-T-Community-DoD-FY16': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Community-DoD-FY16/'},
        'MER-T-Community-DoD-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Community-DoD-FY17/'},
        'MER-T-Community-DoD-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Community-DoD-FY18/'},
        'MER-T-Community-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Community-FY17/'},
        'MER-T-Community-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Community-FY18/'},
        'MER-T-Facility-DoD-FY16': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Facility-DoD-FY16/'},
        'MER-T-Facility-DoD-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Facility-DoD-FY17/'},
        'MER-T-Facility-DoD-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Facility-DoD-FY18/'},
        'MER-T-Facility-FY16': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Facility-FY16/'},
        'MER-T-Facility-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Facility-FY17/'},
        'MER-T-Facility-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Facility-FY18/'},
        'MER-T-Narratives-IM-FY16': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Narratives-IM-FY16/'},
        'MER-T-Narratives-IM-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Narratives-IM-FY17/'},
        'MER-T-Narratives-IM-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Narratives-IM-FY18/'},
        'MER-T-Operating-Unit-Level-IM-FY16': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Operating-Unit-Level-IM-FY16/'},
        'MER-T-Operating-Unit-Level-IM-FY17': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Operating-Unit-Level-IM-FY17/'},
        'MER-T-Operating-Unit-Level-IM-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Operating-Unit-Level-IM-FY18/'},
        'Planning-Attributes-COP-Prioritization-National-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/Planning-Attributes-COP-Prioritization-National-FY18/'},
        'Planning-Attributes-COP-Prioritization-SNU-FY18': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/Planning-Attributes-COP-Prioritization-SNU-FY18/'},
        'MER-R-Facility-DoD-FY16Q1Q2Q3': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-R-Facility-DoD-FY16Q1Q2Q3/'},
    }
    INACTIVE_MER_OCL_EXPORT_DEFS = {
        'MER-T-Community-FY16': {
            'import_batch': IMPORT_BATCH_MER,
            'show_build_row_method': 'build_mer_indicator_output',
            'show_headers_key': 'mer',
            'endpoint': '/orgs/PEPFAR/collections/MER-T-Community-FY16/'},
    }

    # SIMS OCL Export Definitions
    SIMS_OCL_EXPORT_DEFS = {
        'sims_source': {
            'import_batch': IMPORT_BATCH_SIMS,
            'show_build_row_method': 'build_sims_row',
            'show_headers_key': 'sims',
            'endpoint': '/orgs/PEPFAR/sources/SIMS/'},
        'sims2_above_site': {
            'import_batch': IMPORT_BATCH_SIMS,
            'show_build_row_method': 'build_sims_row',
            'show_headers_key': 'sims',
            'endpoint': '/orgs/PEPFAR/collections/SIMS2-Above-Site/'},
        'sims2_community': {
            'import_batch': IMPORT_BATCH_SIMS,
            'show_build_row_method': 'build_sims_row',
            'show_headers_key': 'sims',
            'endpoint': '/orgs/PEPFAR/collections/SIMS2-Community/'},
        'sims2_facility': {
            'import_batch': IMPORT_BATCH_SIMS,
            'show_build_row_method': 'build_sims_row',
            'show_headers_key': 'sims',
            'endpoint': '/orgs/PEPFAR/collections/SIMS2-Facility/'},
        'sims3_above_site': {
            'import_batch': IMPORT_BATCH_SIMS,
            'show_build_row_method': 'build_sims_row',
            'show_headers_key': 'sims',
            'endpoint': '/orgs/PEPFAR/collections/SIMS3-Above-Site/'},
        'sims3_community': {
            'import_batch': IMPORT_BATCH_SIMS,
            'show_build_row_method': 'build_sims_row',
            'show_headers_key': 'sims',
            'endpoint': '/orgs/PEPFAR/collections/SIMS3-Community/'},
        'sims3_facility': {
            'import_batch': IMPORT_BATCH_SIMS,
            'show_build_row_method': 'build_sims_row',
            'show_headers_key': 'sims',
            'endpoint': '/orgs/PEPFAR/collections/SIMS3-Facility/'},
        'sims_option_sets': {
            'import_batch': IMPORT_BATCH_SIMS,
            'show_build_row_method': 'build_sims_option_sets_row',
            'show_headers_key': 'option_sets',
            'endpoint': '/orgs/PEPFAR/collections/SIMS-Option-Sets/'},
    }

    # Mechanisms OCL Export Definitions
    MECHANISMS_OCL_EXPORT_DEFS = {
        'Mechanisms': {
            'import_batch': IMPORT_BATCH_MECHANISMS,
            'show_build_row_method': 'build_mechanism_row',
            'show_headers_key': 'mechanisms',
            'subtitle': 'View of mechanisms, partners, agencies, OUs and start and end dates for each mechanism',
            'endpoint': '/orgs/PEPFAR/sources/Mechanisms/'},
    }

    # Tiered Support OCL Export Definitions
    TIERED_SUPPORT_OCL_EXPORT_DEFS = {
        'dataelements': {
            'import_batch': IMPORT_BATCH_TIERED_SUPPORT,
            'show_build_row_method': 'build_tiered_support_data_element_row',
            'show_headers_key': 'tiered_support_data_elements',
            'endpoint': '/orgs/PEPFAR/sources/Tiered-Site-Support/'},
        'options': {
            'import_batch': IMPORT_BATCH_TIERED_SUPPORT,
            'show_build_row_method': 'build_tiered_support_option_row',
            'show_headers_key': 'tiered_support_options',
            'endpoint': '/orgs/PEPFAR/sources/Tiered-Site-Support/'},
    }
